packages:
  - 'apps/*'
  - 'packages/*'
  - 'e2e/*'

catalog:
  '@types/node': ^22.0.0
  '@supabase/auth-js': 2.71.1-rc.1
  '@supabase/supabase-js': ^2.47.14
  '@supabase/realtime-js': ^2.11.3
  next: ^v15.6.0-canary.8
  'react': '^18.3.0'
  'react-dom': '^18.3.0'
  '@types/react': '^18.3.0'
  '@types/react-dom': '^18.3.0'
  'valtio': '^2.1.7'
  'vite': '^6.2.7'
